### ISSUE TITLE
Lower environmental footprint

### ISSUE THREAD

**Issue by MorganGeek** [MorganGeek/zola-sam#1]
[**ecometer.org report**](http://www.ecometer.org/report?url=https%3A%2F%2Fblog.morgangeek.be%2F) - Successfully passed 13 of 15 best practices tested :

- [x]  #16Provide a print style sheet (but I had to cheat a bit, because of this https://gitlab.com/ecoconceptionweb/ecometer/issues/71)
- [x]  #19Use standard typefaces
- [ ]  #80Use ETags ([how to fix](http://www.ecometer.org/rules/etag-header.html))
- [ ]  #88Minify JavaScript files ([how to fix](http://www.ecometer.org/rules/javascript-minification.html))

**Comment by MorganGeek** [comment]
The issues #80 and #88 cannot be solved currently:
- The issue 80 is related to GitHub pages
- The issue 88 is related to the JavaScript of pages referenced from the blog, because ecometer.org mistakenly includes those websites as part of the test because I reference them.
